"""empty message

Revision ID: 64ffb1e1027f
Revises: 778adc3034ac
Create Date: 2023-07-28 18:59:03.157188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ffb1e1027f'
down_revision = '778adc3034ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realtor_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('QuestionId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'questions', ['QuestionId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realtor_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('QuestionId')

    # ### end Alembic commands ###
