"""empty message

Revision ID: 778adc3034ac
Revises: a7cdabca693b
Create Date: 2023-07-28 18:57:44.627441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '778adc3034ac'
down_revision = 'a7cdabca693b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realtor_task', schema=None) as batch_op:
        batch_op.drop_constraint('realtor_task_ibfk_3', type_='foreignkey')
        batch_op.drop_column('QuestionId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realtor_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('QuestionId', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('realtor_task_ibfk_3', 'questions', ['QuestionId'], ['id'])

    # ### end Alembic commands ###
